### ISSUE TITLE
How to reload new data from SpreadSheet

### ISSUE THREAD

**Issue by htnabe** [EhsanShakil/React-Native-With-Google-Spreadsheet-API#1]
Hello.

I recently started building a very simple smartphone app using ReactNative with your repository as a reference.
I have a very simple question: what's a good way to reload the data updated in the spreadsheet and reflect them in the application side?

I'm pretty new to smartphone app. and ReactNative and only recently started to understand "useState" and "useEffect", and have very little understanding of Redux. 

I've spent the last two days looking for various ways to solve this, but I can't find a solution at all. You are my last hope..please help me :,-(

**Comment by EhsanShakil** [comment]
you can use flatlist to improve the application performance and if you are
just directly implementing through the map and rendering all the data you
can call the API in the useEffect hook and then the state in which you are
getting the data and pass it into the useEffect empty array so in this way
whenever the new data comes useEffect hook will re-render the screen

**Comment by htnabe** [comment]
Thank you for your very quick response!
I'm gonna try it.

**Comment by EhsanShakil** [comment]
Welcome :)
